# docker-compose.yml

version: '3'
services:
  server:
    build: ./server
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app