# .github/workflows/ci.yml

name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install and Test Backend
        working-directory: ./server
        run: |
          npm install
          npm test

      - name: Install and Test Frontend
        working-directory: ./client
        run: |
          npm install
          npm test
